analytics: {}
color:
  brandColors:
    - '#E0D8C0'
    - '#000000'
    - '#887858'
    - '#000000'
    - '#000000'
  brandStrength: 0.799549
  lightness: 0.416666
  rhythmicContrast: 0.832207
  saturation: 0.745495
cta: {}
layout_spectrum: 1
name: Aamir Manisa
opengraph: {}
purpose: {}
typography_spectrum: 0.346846
